import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider as ChakraUiProvider } from "@/components/ui/provider";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";
import LanguageSwitcher from "@/components/common/LanguageSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const locale = await getLocale();

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChakraUiProvider>
          <LanguageSwitcher/>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ChakraUiProvider>
      </body>
    </html>
  );
};

export default RootLayout;
